version: '3.8'

services:
  db:
    image: postgres:17
    container_name: lista-de-tarefas-db-1
    restart: always
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: joaopsilvam
      POSTGRES_PASSWORD: joaopsilvam
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=task_manager;Username=joaopsilvam;Password=joaopsilvam
    ports:
      - "5000:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
